services:
  mineboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mineboard
    env_file:
      - .env
    ports:
      - "5090:5090"
    volumes:
      - /mnt/data/self-host/minecraft-control:/app/data
    restart: unless-stopped
    command: ["gunicorn", "--bind", "0.0.0.0:5090", "--timeout", "120", "--preload", "app:app"]
    networks:
      - minecraft_network

networks:
  minecraft_network:
    external: true